version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - backend

  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./wwwroot/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb:
